name: generator

on:
  push:
    branches: [master]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Update readme
        uses: linuxsuren/yaml-readme@v0.0.16
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pattern: 'data/*.yaml'
          output: README.md
          template: README.tpl
          groupby: kind
          username: linuxsuren
          org: linuxsuren
          repo: awesome-ai
          push: true
